Fix compilation errors on Windows MSVC compiler
- Remove nlohmann/json due to C++ modules compatibility issues. More info at https://github.com/nlohmann/json/issues/3970
- Add winsock2 include in Server's Application module.
  For some reason it needs to be included before SimpleIni
  (even though this package shouldn't have any networking code).
  Error: error C2375: 'shutdown': redefinition; different linkage
  After little research I found out that this error happens when winsock.h is included before
  winsock2.h, that's why now winsock2 is included early.